name: Continuous Integration

on:
  push:
    branches:
      - "*"
      - "!master"
  pull_request:
    branches:
      - "*"

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 20.x

      - name: Install Dependencies
        run: npm ci

      - name: Build the Application
        run: npm run build

      - name: Run Cypress Tests
        run: npm run test:cypress
