name: Continuous Integration

on:
  push:
    branches:
      - "*"
      - "!master"
  pull_request:
    branches:
      - "*"

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: 18.x

      - name: Install Dependencies
        run: npm ci && npm install -g @lhci/cli@0.13.x

      - name: Build the Application
        run: npm run build

      - name: Run Cypress Tests
        run: npm run test:cypress

      - name: Run LightHouse Audit
        run: lhci autorun
