name: Checks + Deployment + Lighthouse Audit

on:
  push:
    branches:
      - "master"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: 20.x

      - name: Install Dependencies
        run: npm ci

      - name: Build the Application
        run: npm run build

      - name: Run Cypress Tests
        run: npm run test:cypress

      - name: Deployment to Prod
        uses: w9jds/firebase-action@v13.22.1
        with:
          args: deploy --only hosting
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

  lighthouse:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: https://billw.space
          runs: 3
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage
